swagger: '2.0'
info:
  version: '1.0'
  description: Manage food carts.
  title: Food Carts API
basePath: /v1/streetcarts
host: llynch-test.apigee.net
schemes:
  - https
securityDefinitions:
   APIKeyHeader:
     type: apiKey
     in: header
     name: x-api-key
   Bearer:
     type: apiKey
     in: header
     name: Authorization
consumes:
  - application/json
produces:
  - application/json
paths:
  '/foodcarts':
    get:
      description: View all food carts.
      operationId: GetFoodCarts
      security:
        - APIKeyHeader: []
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/foodcarts'
    post:
      description: Create a food cart.
      operationId: CreateFoodCart
      security:
        - Bearer: []
      parameters:
        - name: body
          in: body
          required: true
          description: Details for the food cart.
          schema:
            $ref: '#/definitions/foodcartDetails'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/foodcart'
  '/foodcarts/{cart_id}':
    get:
      description: View food cart details.
      operationId: GetFoodCartbyID
      security:
        - APIKeyHeader: []
      parameters:
        - name: cart_id
          in: path
          description: ID of the food cart.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/foodcart'
    put:
      description: Update food cart details.
      operationId: UpdateFoodCart
      security:
        - Bearer: []
      parameters:
        - name: cart_id
          in: path
          required: true
          description: ID of the food cart.
          type: string
        - name: body
          in: body
          required: true
          description: Details to update for the food cart.
          schema:
            $ref: '#/definitions/foodcartDetails'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/foodcart'
    delete:
      description: Delete a food cart.
      operationId: DeleteFoodCart
      security:
        - Bearer: []
      parameters:
        - name: cart_id
          in: path
          description: ID of the food cart.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/foodcart'
  '/foodcarts/{cart_id}/menus':
    get:
      description: View the menus associated with a food cart.
      operationId: GetFoodCartMenus
      security:
        - APIKeyHeader: []
      parameters:
        - name: cart_id
          in: path
          description: ID of the food cart.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menus'
    post:
      description: Add a menu to a food cart.
      operationId: CreateFoodCartMenu
      security:
        - Bearer: []
      parameters:
        - name: cart_id
          in: path
          description: ID of the food cart.
          required: true
          type: string
        - name: body
          in: body
          required: true
          description: Name of the menu.
          schema:
            $ref: '#/definitions/menuName'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menu'
  '/foodcarts/{cart_id}/items':
    get:
      description: View menu items associated with a food cart.
      operationId: GetFoodCartItems
      security:
        - APIKeyHeader: []
      parameters:
        - name: cart_id
          in: path
          description: ID of the food cart.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/items'
    post:
      description: Create a menu item to a food cart.
      operationId: CreateFoodCartItem
      security:
        - Bearer: []
      parameters:
        - name: cart_id
          in: path
          description: ID of the food cart.
          required: true
          type: string
        - name: body
          in: body
          required: true
          description: Details for the menu item.
          schema:
            $ref: '#/definitions/itemDetails'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
definitions:
  foodcarts:
    type: array
    description: List of food carts.
    items:
      properties:
        uuid:
          type: string
          description: ID of the food cart.
        cartname:
          type: string
          description: Name of the food cart.
        city:
          type: string
          description: City where the food cart is located.
  foodcart:
    type: object
    description: Food cart details.
    properties:
      uuid:
        type: string
        description: ID of the food cart.
      cartName:
        type: string
        description: Name of the food cart.
      description:
        type: string
        description: Description of the food cart.
      hours:
        type: string
        description: Hours of operation.
      location:
        type: object
        properties:
          address:
            type: string
            description: Mailing address for the food cart.
          city:
            type: string
            description: City where the food cart is located.
          region:
            type: string
            description: State or region where the food cart is located.
          country:
            type: string
            description: Country where the food cart is located.
          postalCode:
            type: string
            description: Postal code for the food cart.
          latitude:
            type: string
            description: Latitude of the food cart. Required for locating the cart in mapping apps.
          longitude:
            type: string
            description: Longitude of the food cart. Required for locating the cart in mapping apps.
          shortAddress:
            type: string
            description: 'Short description of the food cart location, including landmarks.'
      ownerID:
        type: string
        description: ID of the owner of the food cart.
      phone:
        type: string
        description: Phone number for the food cart.
      url:
        type: string
        description: URL of the food cart.
  foodcartDetails:
    type: object
    properties:
      cartName:
        type: string
        description: Name of the food cart.
      description:
        type: string
        description: Description of the food cart.
      hours:
        type: string
        description: 'Hours of operation. For example: Monday through Saturday: 9-6, Closed Sunday.'
      location:
        type: object
        properties:
          address:
            type: string
            description: Mailing address for the food cart.
          city:
            type: string
            description: City where the food cart is located.
          region:
            type: string
            description: State or region where the food cart is located.
          country:
            type: string
            description: Country where the food cart is located.
          postalCode:
            type: string
            description: Postal code for the food cart.
          latitude:
            type: string
            description: Latitude of the food cart. Required for locating the cart in mapping apps.
          longitude:
            type: string
            description: Longitude of the food cart. Required for locating the cart in mapping apps.
          shortAddress:
            type: string
            description: 'Short description of the food cart location, including landmarks.'
      phone:
        type: string
        description: Phone number for the food cart.
      url:
        type: string
        description: URL of the food cart.
  menus:
    type: array
    description: List of menus.
    items:
      properties:
        uuid:
          type: string
          description: ID of the menu.
        cartID:
          type: string
          description: ID of the food cart.
        menuName:
          type: string
          description: Name of the menu.
  menuName:
    type: object
    required:
      - menuName
    properties:
      menuName:
        type: string
        description: Name of the menu.
  menu:
    type: object
    properties:
      uuid:
        description: ID of the menu.
        type: string
      cartID:
        description: ID of the food cart.
        type: string
      menuName:
        type: string
        description: Name of the menu.
  items:
    type: array
    description: List of menu items.
    items:
      properties:
        uuid:
          type: string
          description: ID of the menu item.
        cartID:
          type: string
          description: ID of the food cart.
        description:
          type: string
          description: Description of the menu item.
        itemName:
          type: string
          description: Name of the menu item.
        price:
          type: number
          description: Price of the menu item.
  item:
    type: object
    description: Menu item details.
    properties:
      uuid:
        type: string
        description: ID of the menu item.
      cartID:
        type: string
        description: ID of the food cart.
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: number
        description: Price of the menu item.
  itemDetails:
    type: object
    properties:
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: string
        description: Price of the menu item.
