swagger: '2.0'
info:
  version: '1.0'
  title: Items API
  description: Manage menu items for a food cart.
basePath: /v1/streetcarts
host: org_name-env.apigee.net
schemes:
  - https
securityDefinitions:
   APIKeyHeader:
     type: apiKey
     in: header
     name: x-api-key
   Bearer:
     type: apiKey
     in: header
     name: Authorization
consumes:
  - application/json
produces:
  - application/json
paths:
  '/items/{item_id}':
    get:
      description: View details for a menu item.
      operationId: Get Menu Item By ID
      security:
        - APIKeyHeader: []
      parameters:
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
    put:
      description: Update a menu item.
      operationId: Update Menu Item
      security:
        - Bearer: []
      parameters:
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
        - name: body
          in: body
          required: true
          description: Updates for the menu item.
          schema:
            $ref: '#/definitions/itemDetails'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
    delete:
      description: Delete a menu item.
      operationId: Delete Menu Item
      security:
        - Bearer: []
      parameters:
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
definitions:
  item:
    type: object
    description: Menu item details.
    properties:
      uuid:
        type: string
        description: ID of the menu item.
      cartID:
        type: string
        description: ID of the food cart.
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: number
        description: Price of the menu item.
  itemDetails:
    type: object
    properties:
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: string
        description: Price of the menu item.
