swagger: '2.0'
info:
  version: '1.0'
  title: Menus API
  description: Manage menus in your food cart.
basePath: /v1/streetcarts
host: org_name-env.apigee.net
schemes:
  - https
securityDefinitions:
   APIKeyHeader:
     type: apiKey
     in: header
     name: x-api-key
   Bearer:
     type: apiKey
     in: header
     name: Authorization
consumes:
  - application/json
produces:
  - application/json
paths:
  '/menus/{menu_id}':
    get:
      description: View details for a menu.
      operationId: Get Menu by ID
      security:
        - APIKeyHeader: []
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menuDetails'
    delete:
      description: Delete a menu.
      operationId: Delete Menu
      security:
        - Bearer: []
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menu'
  '/menus/{menu_id}/items':
    get:
      description: View all items on a menu.
      operationId: Get Items on Menu
      security:
        - APIKeyHeader: []
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/items'
  '/menus/{menu_id}/items/{item_id}':
    put:
      description: Add an item to a menu.
      operationId: Add Item to Menu
      security:
        - Bearer: []
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: item_id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
    delete:
      description: Remove an item from a menu.
      operationId: Remove Item from Menu
      security:
        - Bearer: []
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
definitions:
  menuDetails:
    type: object
    description: Menu details.
    properties:
      uuid:
        description: ID of the menu.
        type: string
      cartID:
        description: ID of the food cart.
        type: string
      menuName:
        type: string
        description: Name of the menu.
      items:
        type: array
        description: List of menu items.
        items:
          properties:
            uuid:
              type: string
              description: ID of the menu item.
            cartID:
              type: string
              description: ID of the food cart.
            description:
              type: string
              description: Description of the menu item.
            itemName:
              type: string
              description: Name of the menu item.
            price:
              type: number
              description: Price of the menu item.
  menu:
    type: object
    properties:
      uuid:
        description: ID of the menu.
        type: string
      cartID:
        description: ID of the food cart.
        type: string
      menuName:
        type: string
        description: Name of the menu.
  items:
    type: array
    description: List of menu items.
    items:
      properties:
        uuid:
          type: string
          description: ID of the menu item.
        cartID:
          type: string
          description: ID of the food cart.
        description:
          type: string
          description: Description of the menu item.
        itemName:
          type: string
          description: Name of the menu item.
        price:
          type: number
          description: Price of the menu item.
  item:
    type: object
    description: Menu item details.
    properties:
      uuid:
        type: string
        description: ID of the menu item.
      cartID:
        type: string
        description: ID of the food cart.
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: number
        description: Price of the menu item.
