swagger: '2.0'
info:
  version: '1.0'
  title: Menus API
  description: Manage menus for a food cart.
basePath: /v1/streetcarts
host: org_name-env.apigee.net
schemes:
  - https
paths:
  '/menus/{menu_id}':
    get:
      description: View details for a menu.
      operationId: GetMenuByID
      produces:
        - application/json
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: x-api-key
          in: header
          description: 'Consumer key for the registered developer application.'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menuDetails'
    delete:
      description: Delete a menu.
      operationId: DeleteMenu
      produces:
        - application/json
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: Authorization
          in: header
          description: 'Pass the access token returned when the user was authenticated as <code>Bearer <i>access-token</i></code>.'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menu'
  '/menus/{menu_id}/items':
    get:
      description: View all items on a menu.
      operationId: GetMenuItems
      produces:
        - application/json
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: x-api-key
          in: header
          description: 'Consumer key for the registered developer application.'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/items'
  '/menus/{menu_id}/items/{item_id}':
    put:
      description: Add an item to a menu.
      operationId: AddMenuItems
      produces:
        - application/json
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: item_id
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          description: 'Pass the access token returned when the user was authenticated as <code>Bearer <i>access-token</i></code>.'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
    delete:
      description: Remove an item from a menu.
      operationId: RemoveMenuItems
      produces:
        - application/json
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
        - name: Authorization
          in: header
          description: 'Pass the access token returned when the user was authenticated as <code>Bearer <i>access-token</i></code>.'
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/delete-menu'
definitions:
  menuDetails:
    description: Menu details.
    properties:
      cartID:
        description: ID of the food cart.
        type: string
      menuName:
        type: string
        description: Name of the menu.
      items:
        type: array
        description: List of menu items.
        items:
          $ref: '#/definitions/item'
      uuid:
        description: ID of the menu.
        type: string
  menu:
    properties:
      cartID:
        description: ID of the food cart.
        type: string
      menuName:
        type: string
        description: Name of the menu.
      uuid:
        description: ID of the menu.
        type: string
  items:
    type: array
    description: List of menu items.
    items:
      $ref: '#/definitions/item'
  item:
    description: Menu item details.
    properties:
      cartID:
        type: string
        description: ID of the food cart.
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: number
        description: Price of the menu item.
      uuid:
        type: string
        description: ID of the menu item.
  delete-menu:
    description: Deleted menu item.
    properties:
      action:
        type: string
        description: Action (delete).
      application:
        type: string
        description: Application ID.
      applicationName:
        type: string
        description: Application name.
      duration:
        type: integer
        description: Duration of the operation.
      entities:
        description: Entity that was deleted.
        properties:
          cartID:
            type: string
            description: ID of the food cart.
          created:
            type: integer
            description: Time the entity was created in epoch format.
          description:
            type: string
            description: Description of the menu item.
          menuName:
            type: string
            description: Name of the menu.
          metadata: 
            type: object
            description: Metadata.
          modified:
            type: integer
            description: Time the entity was deleted in epoch format.
          price:
            type: number
            description: Price of the menu item.
          type:
            type: string
            description: Type of entity.
          uuid:
            type: string
            description: ID of the menu item.
      organization:
        type: string
        description: Organization name.
      params:
        type: object
        description: List of parameters.
      path:
        type: string
        description: Resource path.
      timestamp:
        type: integer
        descrpition: Timestamp in epoch format.
      uri:
        type: string
        description: Resource URI.
